#!/usr/bin/env ruby
# This command will automatically be run when you run "rails" with Rails 3 gems installed from the root of your application.

APP_PATH = File.expand_path('/Users/demisaran/Documents/dimitra/Workspace/collos/config/application.rb',  __FILE__)
require File.expand_path('/Users/demisaran/Documents/dimitra/Workspace/collos/config/boot.rb',  __FILE__)
require 'rails/commands'
